name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  backend_test_phase:
    runs-on: ubuntu-20.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: npm ci
      - run: npm test

  frontend_unit_tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - run: npm run build
      - run: npm run eslint
      - run: npm test

  cypress_e2e_tests:
    needs: ['backend_test_phase', 'frontend_unit_tests']
    runs-on: ubuntu-20.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Install backend dependencies
        run: npm install
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:cli
          start: npm run start:test, npm run start:front
          wait-on: 'http://localhost:3003'
